classes: {
  dup_elem: {
    label: ""
    grid-gap: 0
    grid-columns: 1
  }

  header: {
    shape: text
    style: {
      font-size: 28
      bold: true
      underline: true
    }
  }

  links: {
    shape: text
    style: {
      font-size: 18
      font-color: blue
      underline: true
    }
    label.near: center-left
  }

  links-unmarked: {
    shape: text
    style: {
      font-size: 18
    }
    label.near: center-left
  }
  reference: {
    label: ""
    style: {
      fill: "transparent"
      stroke: "transparent"
    }
    grid-columns: 2
    horizontal-gap: 10
    vertical-gap: 0
  }
  dummy: {
    style.opacity: 0
    shape: rectangle
    width: 1
    height: 1
  }
  jump: {
    shape: circle
    style.fill: "#e53935"
    style.font-color: "white"
    style.font-size: 18
  }
  base: {
    label: ""
    grid-gap: 0
    grid-rows: 3
    grid-columns: 3
  }
}

vars: {
  colors: {
    magenta   : "#ffadad"
    orange    : "#ffd6a5"
    yellow    : "#fdffb6"
    green     : "#caffbf"
    cyan      : "#9bf6ff"
    blue      : "#a0c4ff"
    purple    : "#bdb2ff"
    pink      : "#ffc6ff"
    white     : "#ffffff"
    light_gray: "#cccccc"
    light_grey: "#cccccc"
    red       : "#e53935"
  }
}