...@../classes

any_elem: {
  class: base
  top_left: {
    class: dummy
    width: 1
    height: 1
  }
  top_center: {
    class: dummy
    height: 1
  }
  top_right: {
    class: dummy
    width: 1
    height: 1
  }
  center_left: {
    class: dummy
    width: 1
  }
  elem
  center_right: {
    class: dummy
    width: 1
  }
  bottom_left: {
    class: dummy
    width: 1
    height: 1
  }
  bottom_center: {
    class: dummy
    height: 1
  }
  bottom_right: {
    class: dummy
    width: 1
    height: 1
  }
}

y

any_elem.top_right -> y