...@../classes

any_elem: {
  class: base
  # elem is required to be a var, else will be the first one to be imported instead of in-order
  vars: {
    elem: {
      "elem"
    }
  }
  ...${connection_pos.before_elem}
  ...${elem}
  ...${connection_pos.after_elem}

  # The connections are required to ensure ordering,
  # which otherwise changes based on the element declared in this file first
  top_left -- top_center -- top_right
  center_left -- elem -- center_right
  bottom_left -- bottom_center -- bottom_right

}

y

any_elem.top_right -> y